// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAROvHCitGsoLyRyctvI0FXJudT-wvpwQ4',
    appId: '1:932984179210:web:3240434d39b91ae32d2df3',
    messagingSenderId: '932984179210',
    projectId: 'fullmedcarev1',
    authDomain: 'fullmedcarev1.firebaseapp.com',
    storageBucket: 'fullmedcarev1.firebasestorage.app',
    measurementId: 'G-8E0JV0FN61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPn4aX7VJGM29UdELdm9qiaYdQj-LivoA',
    appId: '1:932984179210:android:cba2133e12db654e2d2df3',
    messagingSenderId: '932984179210',
    projectId: 'fullmedcarev1',
    storageBucket: 'fullmedcarev1.firebasestorage.app',
  );

}